

#spring.datasource.url=jdbc:mysql://ec2-52-33-158-168.us-west-2.compute.amazonaws.com:3306/superbmath_test_db
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.username=octo-user
#spring.datasource.password=hAPEmcHv
#spring.h2.console.enabled=true

jwt.secret=Bq9AzYIB0f6BgPo9jeynoQQbxR1zB50jqb41YjZi938kxUs8g7bqlzC/9PPtHvPVNlhUhWcGB2ToDbX61zW+UU8+bZ9ug2jNkPvwVRgTPtRZZ5AWls/CLMHHVAfHm2Xd4SwL4x25cJyIC6h/YDNgaRvgRqDkwpFPLK4J0M/qH2ZOReaZAWQX
jwt.issuer=Oscar Fimbres
jwt.type=JWT
jwt.audience=superbmath

server.port=5000