cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: us-west-2

dynamodb:
  table-name: dev-archimedes-table

s3:
  activity-bucket-name: dev-archimedes-exercises-bucket
  activity-results-bucket-name: dev-archmimedes-exercise-results-bucket

cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  user-pool-client-id: ${COGNITO_USER_POOL_CLIENT_ID}

mini-quiz-base-url: https://dev-archimedes-exercises-bucket.s3-website-us-west-2.amazonaws.com/

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientName: ${COGNITO_USER_POOL_CLIENT_NAME}
            client-secret: 
            redirect-uri: 'http://localhost:8080/login/oauth2/code/cognito'
            client-id: ${COGNITO_USER_POOL_CLIENT_ID}
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-west-2.amazonaws.com/${COGNITO_USER_POOL_ID}
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.us-west-2.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json

web:
  cors:
    allowedOrigins: 
      - "http://localhost:3000" # Replace with the origin of your client application
    allowedMethods: 
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowedHeaders: 
      - "Content-Type"
      - "Authorization"
      - "Accept"
      - "Access-Control-Allow-Origin"
      - "Access-Control-Allow-Methods"
      - "Access-Control-Allow-Headers"
      - "Access-Control-Allow-Credentials"
    exposedHeaders: 
      - "Custom-Header-1" # Replace with any custom headers your application uses
    maxAge: 3600 # The maximum age (in seconds) of preflight requests. This is 1 hour.

server:
  port: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info