name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    environment: dev
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ vars.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        log-configuration-log-driver: awslogs
        log-configuration-options: |
          awslogs-create-group=true
          awslogs-group=${{ vars.LOG_GROUP }}
          awslogs-region=${{ vars.AWS_REGION }}
          awslogs-stream-prefix=${{ vars.LOGS_STREAM_PREFIX }}
        environment-variables: |
          ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          COGNITO_USER_POOL_ID=${{ vars.COGNITO_USER_POOL_ID }}
          COGNITO_USER_POOL_CLIENT_ID=${{ vars.COGNITO_USER_POOL_CLIENT_ID }}
          COGNITO_USER_POOL_CLIENT_NAME=${{ vars.COGNITO_USER_POOL_CLIENT_NAME }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ vars.SERVICE_NAME }}
        cluster: ${{ vars.CLUSTER_NAME }}
        wait-for-service-stability: true
        wait-for-task-stopped: true