name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}

    - name: Build and push Docker image
      id: build
      env:
        ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build --platform linux/arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .
        echo "::set-output name=image_uri::${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"

    - name: Register new task definition
      needs: build
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
        TASK_DEFINITION: ${{ vars.TASK_DEFINITION }}
        CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
        LOGS_STREAM_PREFIX: ${{ vars.LOGS_STREAM_PREFIX }}
        IMAGE_URI: ${{ needs.build.outputs.image_uri }}
      run: |
        aws ecs register-task-definition \
          --family $TASK_DEFINITION \
          --network-mode awsvpc \
          --container-definitions "[{\"name\":\"$CONTAINER_NAME\",\"image\":\"$IMAGE_URI\",\"cpu\":500,\"memory\":1024,\"essential\":true,\"logConfiguration\":{\"logDriver\":\"awslogs\",\"options\":{\"awslogs-group\":\"/ecs/${TASK_DEFINITION}\",\"awslogs-region\":\"${AWS_REGION}\",\"awslogs-stream-prefix\":\"${LOGS_STREAM_PREFIX}\"}},\"healthCheck\":{\"command\":[\"CMD-SHELL\",\"curl -f http://localhost:80/healthcheck/ || exit 1\"],\"interval\":30,\"timeout\":10,\"retries\":3,\"startPeriod\":30}}]" \
          --region $AWS_REGION

    - name: Deploy to ECS
      env:
        AWS_REGION: ${{ vars.AWS_REGION }}
        CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
        SERVICE_NAME: ${{ vars.SERVICE_NAME }}
        IMAGE_URI: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment --region $AWS_REGION